WaterPurifier/urls.py
from django.contrib import admin
from django.urls import path
from front_panel import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^', include('front_panel.urls')),
    url(r'^', include('backend_panel.urls')),
    url(r'^User_search/$', views.user_search),
    url(r'^registration/$', views.registration),
    url(r'^update_password/$',views.update_password),
    url(r'^verify_link/$', views.verify_link),
    url(r'^login/$',views.login),
    url(r'^logout/$', views.logout),
    url(r'^forgot_password/$',views.forgot_password),
    url(r'^admin_index/$',views.admin_index),
    url(r'^update_admin_profile/$',views.admin_update_profile),
    url(r'^update_admin_password/$',views.admin_update_password),
    url(r'^about/$',views.about),
    url(r'^brand_search/$', views.modal_search),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_panel/urls.py
from django.conf.urls import url
from backend_panel import views


app_name = 'backend_panel'

urlpatterns = [
   url(r'^purifier_brands/$',views.brands),
   url(r'^purifier_modals/$',views.modal_details),
   url(r'^description/$',views.description),
   url(r'^features/$',views.features),
   url(r'^service/$',views.service),
   url(r'^top_brand/$',views.top_brand),
   url(r'^update_brands/$',views.update_brands),
   url(r'^update_top_brand/$',views.update_top_brands),
   url(r'^update_models/$',views.update_models),
   url(r'^update_description/$',views.update_description),
   url(r'^update_features/$',views.update_features),
   url(r'^edit_brands/$', views.edit_brands, name="edit_brands"),
   url(r'^delete_brands/$', views.del_brands, name="delete_brands"),
   url(r'^edit_top_brand/$', views.edit_top_brand, name="edit_top_brand"),
   url(r'^delete_top_brand/$', views.delete_top_brand, name="delete_top_brand"),
   url(r'^edit_models/$', views.edit_models, name="edit_models"),
   url(r'^delete_models/$', views.delete_modals, name="delete_models"),
   url(r'^edit_description/$', views.edit_description, name="edit_description"),
   url(r'^delete_description/$', views.delete_description, name="delete_description"),
   url(r'^edit_features/$', views.edit_features, name="edit_features"),
   url(r'^delete_features/$', views.delete_features, name="delete_features"),
   url(r'^update_service/$',views.update_service),
   url(r'^edit_service/$', views.edit_service, name="edit_service"),
   url(r'^delete_service/$', views.del_service, name="delete_service"),
   url(r'^gallery/$',views.gallery),
   url(r'^brand_detail/$', views.brands_detail,name="brands_detail"),
   url(r'^brand_detail2/$', views.brands_detail2,name="brands_detail2"),
   url(r'^model_detail/$', views.model_detail,name="model_detail"),
   url(r'^service_detail/$',views.service_details),
   url(r'^aquagaurd_parts/$',views.aquagaurd_parts),
   url(r'^update_parts/$',views.update_aquagaurd_parts),
   url(r'^edit_parts/$',views.edit_parts,name="edit_parts"),
   url(r'^delete_parts/$',views.delete_parts,name="delete_parts"),
   url(r'^purifier_parts/$', views.purifier_parts),
   url(r'^purifier_parts2/$', views.purifier_parts2),
   url(r'^parts_detail/$', views.parts_detail, name="parts_detail"),










]

front_panel/urls.py
from django.conf.urls import url
from front_panel import views
app_name = 'front_panel'

urlpatterns=[
  url(r'^home/$',views.index, name="index")
]

backend_panel/models.py
from django.db import models

# Create your models here.
class PurifierBrands(models.Model):
    id = models.AutoField(primary_key=True)
    brands = models.CharField(max_length=225,null=True,unique=True)

class TopBrands(models.Model):
    id  =models.AutoField(primary_key=True)
    brand = models.ForeignKey(PurifierBrands, on_delete=models.CASCADE)
    image = models.CharField(max_length=225,default="",null=True)


class Modals(models.Model):
    id = models.AutoField(primary_key=True)
    brand = models.ForeignKey(PurifierBrands, on_delete=models.CASCADE)
    name = models.CharField(max_length=225,default="",null=True,unique=True)
    image = models.CharField(max_length=225,default="",null=True)
    price = models.CharField(max_length=225,default="",null=True)

class Descriptions(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=225,default="",null=True)
    modal =  models.ForeignKey(Modals, on_delete=models.CASCADE)

class Features(models.Model):
    id = models.AutoField(primary_key=True)
    features = models.CharField(max_length=225,default="",null=True)
    modal =  models.ForeignKey(Modals, on_delete=models.CASCADE)

class ServiceCharges(models.Model):
    id = models.AutoField(primary_key=True)
    service = models.CharField(max_length=225,null=True,unique=True)
    price = models.CharField(max_length=225, default="", null=True)

class Aquagaurd_parts(models.Model):
    id  = models.AutoField(primary_key=True)
    company = models.ForeignKey(PurifierBrands, on_delete=models.CASCADE)
    name = models.CharField(max_length=225,default="", null=True,unique=True)
    quality = models.CharField(max_length=225,default="",null=True)
    image = models.CharField(max_length=225, default="", null=True)
    price = models.CharField(max_length=225,default="",null=True)
    Desc = models.CharField(max_length=225,default="",null=True)

backend_panel/forms.py
from django import forms
from backend_panel.models import PurifierBrands, Modals, Descriptions, Features, ServiceCharges,Aquagaurd_parts,TopBrands

class PurifierBrandsForm(forms.ModelForm):
    class Meta:
        model = PurifierBrands
        exclude = ["id","brands"]

class TopBrandsForm(forms.ModelForm):
    class Meta:
        model = TopBrands
        exclude = ["id","brand","image"]

class ModalsForm(forms.ModelForm):
    class Meta:
        model = Modals
        exclude = ["id","brand","name","image","price"]

class DescriptionsForm(forms.ModelForm):
    class Meta:
        model = Descriptions
        exclude = ["id","description","modal"]

class FeaturesForm(forms.ModelForm):
    class Meta:
        model = Features
        exclude = ["id","features","modal"]

class ServiceChargesForm(forms.ModelForm):
    class Meta:
        model = ServiceCharges
        exclude = ["id","service","price"]

class Aquagaurd_partsForm(forms.ModelForm):
    class Meta:
        model = Aquagaurd_parts
        exclude = ["id","company","name","quality","price","Desc","image"]

backend_panel/views.py
from django.shortcuts import render,HttpResponse, redirect
from backend_panel.forms import PurifierBrandsForm, ModalsForm, DescriptionsForm, FeaturesForm, ServiceChargesForm, Aquagaurd_partsForm,TopBrandsForm
from backend_panel.models import PurifierBrands, Modals, Descriptions, Features, ServiceCharges, Aquagaurd_parts,TopBrands
from django.core.files.storage import FileSystemStorage


# Create your views here.

def brands(request):
    if request.method == "POST":
        form = PurifierBrandsForm(request.POST)
        f = form.save(commit=False)
        f.brands = request.POST['brand']
        f.save()
    return render(request,"PurifierBrands.html")

def modal_details(request):
    data = PurifierBrands.objects.all()
    if request.method == "POST":
        form = ModalsForm(request.POST)
        user_image = None
        try:
            if request.FILES["image"]:
                my_file = request.FILES["image"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                user_image = fs.url(file_name)
                user_image = my_file.name
        except:
            pass
        f = form.save(commit=False)
        f.brand_id = request.POST['brand']
        f.name = request.POST['name']
        f.image = user_image
        f.price = request.POST['price']
        f.save()
    return render(request,"purifier_modals.html",{'data':data})

def top_brand(request):
    data = PurifierBrands.objects.all()
    if request.method == "POST":
        form = TopBrandsForm(request.POST)
        user_image = None
        try:
            if request.FILES["image"]:
                my_file = request.FILES["image"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                user_image = fs.url(file_name)
                user_image = my_file.name
        except:
            pass
        f = form.save(commit=False)
        f.brand_id = request.POST['brand']
        f.image = user_image
        f.save()
    return render(request,"top_brand.html",{'data':data})

def description(request):
    data = Modals.objects.all()
    if request.method == "POST":
        form = DescriptionsForm(request.POST)
        f = form.save(commit=False)
        f.modal_id = request.POST['name']
        f.description = request.POST['description']
        f.save()
    return render(request,"description.html",{'data':data})

def features(request):
    data = Modals.objects.all()
    if request.method == "POST":
        form = FeaturesForm(request.POST)
        f = form.save(commit=False)
        f.modal_id = request.POST['name']
        f.features = request.POST['features']
        f.save()
    return render(request,"features.html",{'data':data})

def update_brands(request):
    data = PurifierBrands.objects.all()
    return render(request,"update_brands.html", {'data': data})

def update_top_brands(request):
    data = TopBrands.objects.all()
    return render(request,"update_top_brand.html", {'data': data})

def update_models(request):
    data = Modals.objects.all()
    return render(request,"update_models.html",{'data':data})

def update_description(request):
    data = Descriptions.objects.all()
    return render(request,"update_description.html",{'data':data})

def update_features(request):
    data = Features.objects.all()
    return render(request,"update_features.html",{'data':data})

def edit_brands(request):
    get_id = request.GET['id']
    if request.method == "POST":
        name = request.POST['brand']
        update = PurifierBrands(id=get_id, brands=name)
        update.save(update_fields=['brands'])
    return render(request, "PurifierBrands.html")

def del_brands(request):
    get_id = request.GET['id']
    data = PurifierBrands.objects.get(id=get_id)
    data.delete()
    return redirect("/update_brands/")

def edit_models(request):
    get_id = request.GET['id']
    data = PurifierBrands.objects.all()
    if request.method == "POST":
        user_image = None
        try:
            if request.FILES["image"]:
                my_file = request.FILES["image"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                user_image = fs.url(file_name)
                user_image = my_file.name
        except:
            pass
        brand = request.POST['brand']
        name = request.POST['name']
        image = user_image
        price = request.POST['price']
        update = Modals(id=get_id, brand_id=brand ,name=name,image=image,price=price)
        update.save(update_fields=['brand_id','name','image','price'])
    return render(request, "purifier_modals.html",{'data':data})

def edit_top_brand(request):
    get_id = request.GET['id']
    data = PurifierBrands.objects.all()
    if request.method == "POST":
        user_image = None
        try:
            if request.FILES["image"]:
                my_file = request.FILES["image"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                user_image = fs.url(file_name)
                user_image = my_file.name
        except:
            pass
        brand = request.POST['brand']
        image = user_image
        update = TopBrands(id=get_id, brand_id=brand ,image=image)
        update.save(update_fields=['brand_id','image'])
    return render(request, "top_brand.html",{'data':data})


def delete_modals(request):
    get_id = request.GET['id']
    data = Modals.objects.get(id=get_id)
    data.delete()
    return redirect("/update_models/")

def delete_top_brand(request):
    get_id = request.GET['id']
    data = TopBrands.objects.get(id=get_id)
    data.delete()
    return redirect("/update_top_brand/")

def edit_description(request):
    get_id = request.GET['id']
    data = Modals.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        description = request.POST['description']
        update = Descriptions(id=get_id, modal_id=name, description=description)
        update.save(update_fields=['modal_id', 'description'])
    return render(request, "description.html",{'data':data})

def delete_description(request):
    get_id = request.GET['id']
    data = Descriptions.objects.get(id=get_id)
    data.delete()
    return redirect("/update_description/")


def edit_features(request):
    get_id = request.GET['id']
    data = Modals.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        features = request.POST['features']
        update = Features(id=get_id, modal_id=name, features=features)
        update.save(update_fields=['modal_id', 'features'])
    return render(request, "features.html",{'data':data})

def delete_features(request):
    get_id = request.GET['id']
    data = Features.objects.get(id=get_id)
    data.delete()
    return redirect("/update_features/")

def service(request):
    if request.method == "POST":
        form = ServiceChargesForm(request.POST)
        f = form.save(commit=False)
        f.service = request.POST['service']
        f.price = request.POST['price']
        f.save()
    return render(request,"service.html")

def update_service(request):
    data = ServiceCharges.objects.all()
    return render(request,"update_service.html",{'data':data})

def edit_service(request):
    get_id = request.GET['id']
    if request.method == "POST":
        name = request.POST['service']
        price = request.POST['price']
        update = ServiceCharges(id=get_id, service=name, price=price)
        update.save(update_fields=['service','price'])
    return render(request, "service.html")

def del_service(request):
    get_id = request.GET['id']
    data = ServiceCharges.objects.get(id=get_id)
    data.delete()
    return redirect("/update_service/")

def gallery(request):
    data = Modals.objects.all()
    return render(request,"gallery.html",{'data':data})

def brands_detail(request):
    if request.session['email']!="":
        data = PurifierBrands.objects.all()
        bd_data = []
        c = 0
        for i in data:
            if c == 5:
                break
            bd_data.append(i)
            c += 1
        get_id = request.GET['id']
        brands_data = PurifierBrands.objects.get(id=get_id)
        model_data = Modals.objects.filter(brand_id=get_id)
        d = 0
        md_data = []
        for j in model_data:
            if d == 16:
                break
            md_data.append(j)
            d += 1
        return render(request, "brands_detail.html",{'data': data, 'bd_data': bd_data, 'brands_data': brands_data, 'md_data': md_data})
    else:
        return HttpResponse("Please login to access this page")



def brands_detail2(request):
    data = PurifierBrands.objects.all()
    bd_data = []
    c = 0
    for i in data:
        if c == 5:
            break
        bd_data.append(i)
        c += 1
    get_id = request.GET['id']
    brands_data = PurifierBrands.objects.get(id=get_id)
    model_data = Modals.objects.filter(brand_id=get_id)
    d = 0
    md_data = []
    for j in model_data:
        if d >= 16:
          md_data.append(j)
        d += 1
    return render(request, "brands_detail.html",{'data': data, 'bd_data': bd_data, 'brands_data': brands_data, 'md_data': md_data})

def service_details(request):
    data = PurifierBrands.objects.all()
    bd_data = []
    c = 0
    for i in data:
        if c == 5:
            break
        bd_data.append(i)
        c += 1
    ser_data = ServiceCharges.objects.all()
    return render(request,"service_detail.html",{'data':data,'bd_data':bd_data,'ser_data':ser_data})

def aquagaurd_parts(request):
    data = PurifierBrands.objects.all()
    if request.method == "POST":
        form = Aquagaurd_partsForm(request.POST)
        user_image = None
        try:
            if request.FILES["image"]:
                my_file = request.FILES["image"]
                fs = FileSystemStorage()

backend_panel/templates/Aquagaurd_parts.html
{% extends 'admin-masterpage.html' %}

{% block title %}
Add Aquagaurd_Parts
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Add Aquagaurd_parts</span>
        </div>
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                 <div class="form-group">
                     <label>Brand:</label>
                     <select name="brand">
                         <option value="0">Select</option>
                         {% if data %}
                         {% for i in data %}
                         <option value="{{i.id}}">{{ i.brands }}</option>
                         {% endfor %}
                         {% endif %}
                     </select>
                 </div>
                <div class="form-group">
                    <label>Part_Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Part Name">
                </div>
                <div class="form-group">
                    <label>Add Image:</label>
                    <input type="file" name="image" placeholder="Image">
                </div>
                <div class="form-group">
                    <label>Quality:</label>
                    <input type="text" class="form-control" name="quality" placeholder="quality">
                </div>
                <div class="form-group">
                    <label>Price:</label>
                    <input type="text" class="form-control" name="price" placeholder="Price">
                </div>
                <div class="form-group">
                    <label>Description:</label>
                    <input type="text" class="form-control" name="Desc" placeholder="Description">
                </div>
                <div class="form-group">
                    <input type="submit" value="Add Parts " class="btn btn-primary btn-block">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/PurifierBrands.html
{% extends 'admin-masterPage.html' %}
{% block title %}
Add Water Purifier Brands
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Add Brands</span>
        </div>
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Brand</label>
                    <input type="text" class="form-control" name="brand" placeholder="Brand">
                </div>
                <div>
                    <input type="submit" value="Add Brand" class="btn btn-primary btn-block">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend_panel/templates/description.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Add Description
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Add Description</span>
        </div>
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Modal</label>
                    <select name="name">
                        <option value="0">Select</option>
                        {% if data  %}
                        {% for i in data %}
                        <option value="{{i.id}}">{{i.name}}</option>
                        {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input type="text" class="form-control" name="description" placeholder="Description">
                </div>
                <div>
                    <input type="submit" value="Add_Description" class="btn btn-primary btn-block">
                </div>
            </form>
    </div>
</div>

{% endblock %}

backend_panel/templates/features.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Add Features
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Add Features</span>
        </div>
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Modal</label>
                    <select name="name">
                        <option value="0">Select</option>
                        {% if data  %}
                        {% for i in data %}
                        <option value="{{i.id}}">{{i.name}}</option>
                        {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="form-group">
                    <label>Features</label>
                    <input type="text" class="form-control" name="features" placeholder="Features">
                </div>
                <div>
                    <input type="submit" value="Add_Feature" class="btn btn-primary btn-block">
                </div>
            </form>
    </div>
</div>

{% endblock %}

backend_panel/templates/service.html
{% extends 'admin-masterPage.html' %}
{% block title %}
Add Service
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Add Service</span>
        </div>
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Service</label>
                    <input type="text" class="form-control" name="service" placeholder="Service">
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <input type="text" class="form-control" name="price" placeholder="Price">
                </div>
                <div>
                    <input type="submit" value="Add Service" class="btn btn-primary btn-block">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend_panel/templates/update_brands.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Brands
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Brands</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Brands</th>
                    <th>  Modify</th>
                </tr>
                {% if data %}
            {% for name in data %}
                <tr>
                <td>{{ name.brands }}</td>
                    <td><a href="{% url 'backend_panel:delete_brands' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                        <a href="{% url 'backend_panel:edit_brands' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
</table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_description.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Description
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Description</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Description</th>
                    <th>Modify</th>
                </tr>
                {% if data %}
                {% for name in data %}
                <tr>
                    <td>{{ name.description }}</td>
                    <td><a href="{% url 'backend_panel:delete_description' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'backend_panel:edit_description' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_features.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Features
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Features</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Features</th>
                    <th>Modify</th>
                </tr>
                {% if data %}
                {% for name in data %}
                <tr>
                    <td>{{ name.features }}</td>
                    <td><a href="{% url 'backend_panel:delete_features' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'backend_panel:edit_features' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
               {% endfor %}
               {% endif %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_models.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Models
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Models</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Brands</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Modify</th>
                </tr>
                {% if data %}
                {% for name in data %}
                <tr>
                    <td>{{ name.brand_id }}</td>
                    <td>{{ name.name}}</td>
                    <td>{{name.image}}</td>
                    <td>{{name.price}}</td>
                    <td><a href="{% url 'backend_panel:delete_models' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'backend_panel:edit_models' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_parts.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Aquagaurd_parts
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Aquagaurd parts</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Brands</th>
                    <th>Part_Name</th>
                    <th>Image</th>
                    <th>Quality</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Modify</th>

                </tr>
                {% if data %}
                {% for name in data %}
                <tr>
                    <td>{{ name.company_id }}</td>
                    <td>{{ name.name}}</td>
                    <td>{{name.image}}</td>
                    <td>{{name.quality}}</td>
                    <td>{{name.price}}</td>
                    <td>{{name.Desc}}</td>
                    <td><a href="{% url 'backend_panel:delete_parts' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'backend_panel:edit_parts' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_service.html
{% extends 'admin-masterPage.html' %}

{% block title %}
Update Service
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Service</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Service type</th>
                    <th> Price </th>
                    <th>  Modify</th>
                </tr>
                {% if data %}
            {% for name in data %}
                <tr>
                    <td>{{ name.service }}</td>
                    <td>{{ name.price }}</td>
                    <td><a href="{% url 'backend_panel:delete_service' %}?id={{name.id}}" class="btn btn-danger">Delete</a>
                        <a href="{% url 'backend_panel:edit_service' %}?id={{name.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
</table>
        </div>
    </div>
</div>

{% endblock %}

backend_panel/templates/update_top_brand.html
{% extends 'admin-masterPage.html' %}
{% block title %}
Update Top Brand Image
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 h1 text-center">
            <span>Update Top Brand Image</span>
        </div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <tr>
                    <th>Image</th>
                    <th>  Modify</th>
                </tr>
                {% if data %}
            {% for i in data %}
                <tr>
                <td>{{ i.image }}</td>
                    <td><a href="{% url 'backend_panel:delete_top_brand' %}?id={{i.id}}" class="btn btn-danger">Delete</a>
                        <a href="{% url 'backend_panel:edit_top_brand' %}?id={{i.id}}" class="btn btn-warning">Edit</a></td>
                </tr>
            {% endfor %}
            {% endif %}
</table>
        </div>
    </div>
</div>
{% endblock %}