WaterPurifier/urls.py
from django.contrib import admin
from django.urls import path
from front_panel import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^', include('front_panel.urls')),
    url(r'^', include('backend_panel.urls')),
    url(r'^User_search/$', views.user_search),
    url(r'^registration/$', views.registration),
    url(r'^update_password/$',views.update_password),
    url(r'^verify_link/$', views.verify_link),
    url(r'^login/$',views.login),
    url(r'^logout/$', views.logout),
    url(r'^forgot_password/$',views.forgot_password),
    url(r'^admin_index/$',views.admin_index),
    url(r'^update_admin_profile/$',views.admin_update_profile),
    url(r'^update_admin_password/$',views.admin_update_password),
    url(r'^about/$',views.about),
    url(r'^brand_search/$', views.modal_search),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_panel/urls.py
from django.conf.urls import url
from backend_panel import views


app_name = 'backend_panel'

urlpatterns = [
   url(r'^purifier_brands/$',views.brands),
   url(r'^purifier_modals/$',views.modal_details),
   url(r'^description/$',views.description),
   url(r'^features/$',views.features),
   url(r'^service/$',views.service),
   url(r'^top_brand/$',views.top_brand),
   url(r'^update_brands/$',views.update_brands),
   url(r'^update_top_brand/$',views.update_top_brands),
   url(r'^update_models/$',views.update_models),
   url(r'^update_description/$',views.update_description),
   url(r'^update_features/$',views.update_features),
   url(r'^edit_brands/$', views.edit_brands, name="edit_brands"),
   url(r'^delete_brands/$', views.del_brands, name="delete_brands"),
   url(r'^edit_top_brand/$', views.edit_top_brand, name="edit_top_brand"),
   url(r'^delete_top_brand/$', views.delete_top_brand, name="delete_top_brand"),
   url(r'^edit_models/$', views.edit_models, name="edit_models"),
   url(r'^delete_models/$', views.delete_modals, name="delete_models"),
   url(r'^edit_description/$', views.edit_description, name="edit_description"),
   url(r'^delete_description/$', views.delete_description, name="delete_description"),
   url(r'^edit_features/$', views.edit_features, name="edit_features"),
   url(r'^delete_features/$', views.delete_features, name="delete_features"),
   url(r'^update_service/$',views.update_service),
   url(r'^edit_service/$', views.edit_service, name="edit_service"),
   url(r'^delete_service/$', views.del_service, name="delete_service"),
   url(r'^gallery/$',views.gallery),
   url(r'^brand_detail/$', views.brands_detail,name="brands_detail"),
   url(r'^brand_detail2/$', views.brands_detail2,name="brands_detail2"),
   url(r'^model_detail/$', views.model_detail,name="model_detail"),
   url(r'^service_detail/$',views.service_details),
   url(r'^aquagaurd_parts/$',views.aquagaurd_parts),
   url(r'^update_parts/$',views.update_aquagaurd_parts),
   url(r'^edit_parts/$',views.edit_parts,name="edit_parts"),
   url(r'^delete_parts/$',views.delete_parts,name="delete_parts"),
   url(r'^purifier_parts/$', views.purifier_parts),
   url(r'^purifier_parts2/$', views.purifier_parts2),
   url(r'^parts_detail/$', views.parts_detail, name="parts_detail"),










]

front_panel/urls.py
from django.conf.urls import url
from front_panel import views
app_name = 'front_panel'

urlpatterns=[
  url(r'^home/$',views.index, name="index")
]

templates/Purifier_parts.html
{% extends "masterPage.html" %}
{% block title %}
Purifier Parts
{% endblock %}
{% block content %}

<div style="background-color:rgba(200,200,200,0.8);height:100%;width:100%;">

    <div class="col-sm-12 h1 text-center" style="background-color:rgba(225,40,50,1); height:80px; margin-top:0px; color:white; margin-bottom:30px;padding-top:18px;"><h1>Purifier Parts</h1></div>
    <div class="container" >
    <div class="row">
        {% for i in p_data %}
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail" >
                <img src="../media/{{ i.image }}" alt="/" style="height:150px; width:200px; ">
                <div class="caption">
                     <h4 style="font-weight:bold;">{{ i.name|slice:"20" }}</h4>
                    <p>{{ i.price }}</p>
                    <div class="hua" style="height:36px; width:214px; background-color:#23b5b9; padding-left:63px; padding-top:7px; margin-left:8px;"><a href="{% url 'backend_panel:parts_detail' %}?id={{i.id}}"  style="color:white; font-style:bold">Click here!</a></div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
</div>
<nav aria-label="...">
  <ul class="pager">
    <li><a href="/purifier_parts/">Previous</a></li>
    <li><a href="/purifier_parts2/">Next</a></li>
  </ul>
</nav>

{% endblock %}

templates/about.html
{% extends "masterPage.html" %}
{% block title %}
About
{% endblock %}
{% block content %}
<div class="col-sm-12 h1 text-center" style="background-color:rgba(225,40,50,1); height:80px; margin-top:0px; color:white; margin-bottom:30px;padding-top:18px;"><h1>ABOUT US</h1></div>
<div style="background-color:white; height:940px;">
    <div style="padding-left:30px;padding-right:40px;">
        <p style="color:black;font-size:16px;">N.A Alkaline Water Purifier Is One Of The Trusted & Independent Water Purifier Service Provider In Chandigarh. At N.A Alkaline, We Offer A Complete Solution Such As Water Purifier Installation, Water Purifier Repair, Maintenance And Any Service For Domestic, Commercial & Industrial Water Purifier. We Deal In All Brands Of Water Purifier At A Relatively Low Price</p>
    </div>
    <div style="padding-left:30px;padding-right:40px;padding-top:20px;" >
        <p style="color:black;font-size:16px;">At N.A Alkaline, we understand that pure water is the only weapon to fight against thousands of diseases out in the real world. With a wealth of experiences accumulated, we trade and supply water treatment products. While we take cares of all your RO(Reverse Osmosis) System, we also ensure that the services provided by us must also satisfy the customer. Our goal is to be the best at what we are providing i.e. a high quality product at a fair price.
    </div>

    <div style="padding-left:20px;padding-top:30px;padding-bottom:30px;height:350px;">
        <div class="col-md-6 w3_footer_grid" style="padding-left:100px;padding-right:80px;">
            <h2 style="color:black;border-bottom:1px solid #d5d5d5;text-align:center;">Contact Us</h2>
            <a href="#"><i class="fa fa-map-marker" style="padding-top:20px;padding-bottom:10px;padding-left:50px;"></i>&nbsp;Location :</a>
            <p style="color:black;padding-left:50px;">Unit No. 221-222 Tower B-4 Spaze I-Tech Park Sector 49, Gurgaon, Haryana 122002</p>
            <a href="#"><i class="fa fa-phone"  style="padding-bottom:10px;padding-left:50px;"></i>&nbsp;Phone Number :</a>
            <p style="color:black;padding-left:50px;">+9888074267,&nbsp;  +9988044267</p>
            <a href="#"><i class="fa fa-envelope"  style="padding-bottom:10px;padding-left:50px;"></i>&nbsp;Email :</a>
            <p style="color:black;padding-left:50px;">123@gmail.com</p>
        </div>

        <div class="col-md-6 w3_footer_grid" style="padding-left:60px;padding-right:110px;">
            <h2 style="color:black;border-bottom:1px solid #d5d5d5;text-align:center;">Services</h2>
            {% if sr_data %}
            <div style="padding-top:20px;">
            {% for i in sr_data %}
            <p style="color:black;padding-left:178px;font-size:18px;">{{ i.service }}</p>
            {% endfor %}
            </div>
            {% endif %}

        </div>
    </div>
    <div style="padding-top:20px;padding-right:40px;padding-bottom:15px;"><h2 style="padding-left:80px;padding-bottom:10px;">Get The Best Water Purifier Repair and Service in Chandigarh</h2>
        <p style="padding-left:30px;font-size:15px;color:black;padding-bottom:20px;">If you want to purchase the water purifier machine and water softener filter then visit the nearest NeelAkash Enterprise and install both water purifier along with the water softener filter. There are the various brands of water purifier filter is available but you have to choose best water purifier for the purest form of water. N.A Alkaline provides you best water purifier in Chandigarh for home use as well as industrial use. Because of the best water purifiers contains high-quality spare parts and gives you maximum purest form of water. </p>
    </div>
    <div style="background:#0a408a; height:150px;text-align:center; width:100%;padding-bottom:150px;">
        <div style="padding-top: 30px;"><span style="font-size: 23px;width:50%;text-align: right;color: rgb(255, 255, 255);line-height: 35px;padding-top:20px;">We provide all brands water purifiers repair service, installation and maintenance work to</span><p style="font-size: 30px;color: rgb(255, 255, 255);">Chandigarh,Panchkula,Mohali,Kharar,Zirakpur.</p>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/admin_index.html
{% extends 'admin-masterPage.html' %}
{% block title %}
Admin Index
{% endblock %}
{% block content %}
<!--four-grids here-->
		<div class="four-grids">
					<div class="col-md-3 four-grid">
						<div class="four-agileits">
							<div class="icon">
								<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>User</h3>
								<h4>{{ user_count }}</h4>

							</div>

						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-agileinfo">
							<div class="icon">
								<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Brands</h3>
								<h4>{{ brand_data }}</h4>

							</div>

						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-w3ls">
							<div class="icon">
								<i class="glyphicon glyphicon-folder-open" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Modals</h3>
								<h4>{{ model_data }}</h4>

							</div>

						</div>
					</div>
					<div class="col-md-3 four-grid">
						<div class="four-wthree">
							<div class="icon">
								<i class="glyphicon glyphicon-briefcase" aria-hidden="true"></i>
							</div>
							<div class="four-text">
								<h3>Service Type</h3>
								<h4>{{ service_data }}</h4>

							</div>

						</div>
					</div>
					<div class="clearfix"></div>
				</div>
<!--//four-grids here-->
<!--photoday-section-->


                    	<div class="col-sm-4 wthree-crd">
                            <div class="card">
                                <div class="card-body">
                                    <div class="widget widget-report-table">
                                        <header class="widget-header m-b-15">
                                        </header>

                                        <div class="row m-0 md-bg-grey-100 p-l-20 p-r-20">
                                            <div class="col-md-6 col-sm-6 col-xs-6 w3layouts-aug">
                                                <h2>USERS</h2>

                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-6 ">
                                                <h3 class="text-right c-teal f-300 m-t-20">Report</h3>
                                            </div>
                                        </div>

                                        <div class="widget-body p-15" style="overflow:scroll;height:519px;">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr style= "overflow: scroll">
                                                        <th>Name</th>
                                                        <th>Email</th>
                                                        <th>Mobile no.</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% if data %}
                                                    {% for i in data %}
                                                    <tr>
                                                        <td>{{ i.name }}</td>
                                                        <td>{{ i.email }}</td>
                                                        <td>{{ i.mobile }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                    {% endif %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4 w3-agileits-crd">

                            <div class="card card-contact-list">
							<div class="agileinfo-cdr">
                                <div class="card-header">
                                    <h3>Models</h3>
                                </div>
                                <div class="card-body p-b-20" style="overflow:scroll;height:519px;">
                                    {% if m_data %}
                                    {% for j in m_data %}
                                    <div class="list-group" >
                                        <a class="list-group-item media" href="">
                                             <div class="pull-left">
                                                <img class="lg-item-img" src="../media/{{ j.image }}" alt="">
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-left">
                                                	<div class="lg-item-heading">{{ j.name }}</div>
                                                	<small class="lg-item-text">{{ j.price }}</small>
                                                </div>
                                                {% if b_data %}
                                                {% for k in b_data %}
                                                {% if j.brand_id == k.id %}

                                                <div class="pull-right">
                                                	<div class="lg-item-heading">{{ k.brands }}</div>
                                                </div>
                                                {% endif %}
                                                {% endfor %}
                                                {% endif %}
                                            </div>
                                        </a>
                                   	</div>
                                    {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
							</div>
                      	</div>

                        <div class="col-sm-4 w3-agileits-crd">

                            <div class="card card-contact-list">
							<div class="agileinfo-cdr">
                                <div class="card-header">
                                    <h3>Parts</h3>
                                </div>
                                <div class="card-body p-b-20" style="overflow:scroll;height:519px;">
                                    {% if p_data %}
                                    {% for j in p_data %}
                                    <div class="list-group">
                                        <a class="list-group-item media" href="">
                                             <div class="pull-left">
                                                <img class="lg-item-img" src="../media/{{ j.image }}" alt="">
                                            </div>
                                            <div class="media-body">
                                                <div class="pull-left">
                                                	<div class="lg-item-heading">{{ j.name }}</div>
                                                	<small class="lg-item-text">{{ j.price }}</small>
                                                </div>
                                                {% if b_data %}
                                                {% for k in b_data %}
                                                {% if j.company_id == k.id %}

                                                <div class="pull-right">
                                                	<div class="lg-item-heading">{{ k.brands }}</div>
                                                </div>
                                                {% endif %}
                                                {% endfor %}
                                                {% endif %}
                                            </div>
                                        </a>
                                   	</div>
                                    {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
							</div>
                      	</div>








	<!--//photoday-section-->
	<!--w3-agileits-pane-->

	  <!--//w3-agileits-pane-->
{% endblock %}

templates/brands_detail.html
{% extends 'masterPage.html' %}
{% block title %}
{% if brands_data %}
{{ brands_data.brand }}
{% endif %}
{% endblock %}
{% block content %}

<div style="background-color:rgba(200,200,200,0.8);height:100%;width:100%;">
    {% if brands_data %}
    <div class="col-sm-12 h1 text-center" style="background-color:rgba(225,40,50,1); height:80px; margin-top:0px; color:white; margin-bottom:30px;padding-top:18px;"><h1>{{ brands_data.brands }}</h1></div>
    {% endif %}
    <div class="container" >
    <div class="row">
        {% for i in md_data %}
        <div class="col-sm-6 col-md-3" >
            <div class="thumbnail"   >
                <div class="caption">
                    <img src="../media/{{ i.image }}" alt="/" style="height:150px; width:200px; padding-left:30px;">
                    <h4 style="font-weight:bold;">{{ i.name|slice:"20" }}</h4>
                    <p>{{ i.price }}</p>
                    <div class="hua" style="height:36px; width:214px; background-color:#23b5b9; padding-left:63px; padding-top:7px; margin-left:8px;"><a href="{% url 'backend_panel:model_detail' %}?id={{i.id}}" style="color:white; font-style:bold">Click here!</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

</div>
 {% if brands_data %}
<nav aria-label="...">
  <ul class="pager">
    <li><a href="{% url 'backend_panel:brands_detail' %}?id={{brands_data.id}}">Previous</a></li>
    <li><a href="{% url 'backend_panel:brands_detail2' %}?id={{brands_data.id}}">Next</a></li>
  </ul>
</nav>
{% endif %}



{% endblock %}

templates/masterPage.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}
{% endblock %}</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
	function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!-- Custom Theme files -->
<link href="/assets/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/assets/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="/assets/css/fasthover.css" rel="stylesheet" type="text/css" media="all" />
<link href="/assets/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- font-awesome icons -->
<link href="/assets/css/font-awesome.css" rel="stylesheet">
<!-- //font-awesome icons -->
<!-- js -->
<script src="/assets/js/jquery.min.js"></script>
<link rel="stylesheet" href="/assets/css/jquery.countdown.css" /> <!-- countdown -->
<!-- //js -->
<!-- web fonts -->
<link href='//fonts.googleapis.com/css?family=Glegoo:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //web fonts -->
<!-- start-smooth-scrolling -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
	$(document).ready(function(){
  $(".toggle").click(function(){
    $(".log").toggle();
  });
</script>
<!-- //end-smooth-scrolling -->
</head>
<body>
<!-- for bootstrap working -->
<script type="text/javascript" src="/assets/js/bootstrap-3.1.1.min.js"></script>
<!-- //for bootstrap working -->
<!-- header modal -->
<div class="modal fade" id="myModal88" tabindex="-1" role="dialog" aria-labelledby="myModal88"
	 aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content"  style="width:740px; padding-left:80px;">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;</button>
				<h4 class="modal-title" id="myModalLabel">Don't Wait, Login now!</h4>
			</div>
			<div class="modal-body modal-body-sub">
				<div class="row">
					<div class="col-md-8 modal_body_left modal_body_left1">
						<div class="sap_tabs">
							<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
								<ul>
									<li class="resp-tab-item" aria-controls="tab_item-0"><span>Sign in</span></li>
									<li class="resp-tab-item" aria-controls="tab_item-1"><span>Sign up</span></li>
								</ul>
								<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
									<div class="facts">
										<div class="register">
											<form action="/login/" method="post">
												{% csrf_token %}
												<input name="email" placeholder="Email Address" type="text" required="">
												<input name="password" placeholder="Password" type="password" required="">
												<div class="sign-up">
													<input type="submit" value="Sign in"/>
												</div>
											</form>
										</div>
									</div>
									<div class="forget"><a href="/forgot_password/"><span>Forgotten Password?</span></a></div>
								</div>

								<div class="tab-2 resp-tab-content" aria-labelledby="tab_item-1">
									<div class="facts">
										<div class="register">
											<form action="/registration/" method="post">
												{% csrf_token %}
												<input placeholder="Name" name="name" type="text" required="">
												<input placeholder="Email Address" name="email" type="email" required="">
												<input placeholder="Mobile" name="mobile" type="text" required="">
												<input placeholder="Address" name="address" type="text" required="">
												<div class="sign-up">
													<input type="submit" value="Create Account"/>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
						<script src="/assets/js/easyResponsiveTabs.js" type="text/javascript"></script>
						<script type="text/javascript">
								$(document).ready(function () {
									$('#horizontalTab').easyResponsiveTabs({
										type: 'default', //Types: default, vertical, accordion
										width: 'auto', //auto or any width like 600px
										fit: true   // 100% fit in a container
									});
								});
							</script>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
<script>
		$('#myModal88').modal('hide');
	</script>
<!-- header modal -->
<!-- header -->
<div class="header" id="home1">
	<div class="container">
		<div class="w3l_login">
			<a href="#" data-toggle="modal" data-target="#myModal88"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
		</div>
		<div class="w3l_logo">
			<h1><a href="{% url 'front_panel:index' %}">N.A Alkaline Water Purifier<span>Drink pure. Live more</span></a></h1>
		</div>
		<div class="search">
			<input class="search_box" type="checkbox" id="search_box">
			<label class="icon-search" for="search_box"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></label>
			<div class="search_form">
				<form action="/brand_search/" method="post">
					{% csrf_token %}
					<input type="text" name="search" placeholder="Search...">
					<input type="submit" value="Send">
				</form>
			</div>
		</div>
	</div>
</div>
<!-- //header -->
<!-- navigation -->
<div class="navigation">
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header nav_2">
				<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'front_panel:index' %}" class="act">Home</a></li>
					<!-- Mega Menu -->
					<li><a href="/about/">About Us</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Water Purifier <b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-3">
							<div class="row" >
								<div class="col-sm-2">
									<ul class="multi-column-dropdown">
										<h6>Brands</h6>
										{% if data %}
										{% for i in data %}
										<li><a href="{% url 'backend_panel:brands_detail' %}?id={{i.id}}">{{ i.brands }}</a></li>
										{% endfor %}
										{% endif %}
									</ul>
								</div>
								<div class="col-sm-3">
									<div class="w3ls_products_pos">
										<h4 style="padding-left:230px;">30%<i>Off/-</i></h4>
										<img style="height:180px;" src="/assets/images/kent_model.jpg" alt=" " class="img-responsive" />
									</div>
								</div>
								<div class="col-sm-4" style="padding-top:60px;">
									<div class="w3ls_products_pos">
										<img style="height:180px;" src="/assets/images/Blue_model.jpg" alt=" " class="img-responsive" />
									</div>
								</div>
								<div class="col-sm-5" style="padding-top:60px;margin-right:-200px;">
									<div class="w3ls_products_pos">
										<img style="height:180px;" src="/assets/images/ao-smith_model.png" alt=" " class="img-responsive" />
									</div>
								</div>

							</div>
						</ul>
					</li>
					<li><a href="/service_detail/">Purifier Service</a></li>
					<li><a href="/purifier_parts/">Purifier Parts</a></li>
				</ul>
			</div>
		</nav>
	</div>
</div>
{% block content %}
{% endblock %}
<!-- //navigation -->
<div class="footer" style="background-color:black;" >
	<div class="container" >
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3 style="color:white;">Contact</h3>
				<p>Call for the better type of services for water purifiers than Anywhere</p>
				<ul class="address">
					<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>1234k Avenue, 4th block, <span>New York City.</span></li>
					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3 style="color:white;">Information</h3>
				<ul class="info">
					<li><a href="/about/">About Us</a></li>


				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3 style="color:white;">Brands</h3>
				<ul class="info">
					{% if bd_data %}
					    {% for i in bd_data %}
					    <li><a href="{% url 'backend_panel:brands_detail' %}?id={{i.id}}">{{ i.brands }}</a></li>
					    {% endfor %}
					{% endif %}
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3 style="color:white;">Profile</h3>

				<ul class="info">
					<li><a href="/home/">Home</a></li>
					<li><p>We provide services in the Chandigarh,Panchkula,Mohali,Kharar,Zirakpur</p></li>

				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

	<div class="footer-copy1">
			<div class="footer-copy-pos">
				<a href="#home1" class="scroll"><img src="/assets/images/arrow.png" alt=" " class="img-responsive" /></a>
			</div>
		</div>
	</div>

<!-- //footer -->
<!-- cart-js -->
<script src="/assets/js/minicart.js"></script>
<script>
        w3ls.render();

        w3ls.cart.on('w3sb_checkout', function (evt) {
        	var items, len, i;

        	if (this.subtotal() > 0) {
        		items = this.items();

        		for (i = 0, len = items.length; i < len; i++) {
        		}
        	}
        });
    </script>
<!-- //cart-js -->
</body>
</html>

templates/parts_detail.html
{% extends 'masterPage.html' %}
{% block title %}
{% endblock %}
{% block content %}
<div class="piche" style="height:500px;">
    {% if  p_data %}
    <div class="col-sm-12 h1 text-center" style="background-color:rgba(225,40,50,1); height:80px; margin-top:0px; color:white; margin-bottom:30px;padding-top:18px;"><h1>{{ p_data.name }}</h1></div>
    <div>
        <img  src="../media/{{ p_data.image }}" alt="/" style="height:250px; width:250px; float:left; margin-left:100px; margin-right:100px;">
        <p style="font-weight:bold; padding-top:135px; font-size:25px;">{{ p_data.name }}</p>
        <p style="padding-top:55px; color:blue; font-weight:bold; font-size:16px;">Price: {{ p_data.price }}</p>
        <div style="width:1000px;"><p style="padding-top:15px; color:black; font-size:18px; font-weight:bold; ">Quality:</p>
            {{ p_data.quality}}
            <p> </p>
        </div>
        <div style="width:1000px;"><p style="padding-top:15px; color:black; font-size:18px; font-weight:bold; ">Desc:</p>
            {{ p_data.Desc}}
            <p> </p>
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}